# Generated by Django 6.0.2 on 2026-02-26 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_connection'),
        ),
    ]
